name: Update AppleBlox Casks

on:
  schedule:
    - cron: "0 0 * * *" # Run daily
  workflow_dispatch: # Allow manual trigger
  workflow_call: # Allow triggering from other workflows

jobs:
  bump-casks:
    name: Update AppleBlox Casks
    runs-on: macos-26
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "::group::System Information"
          echo "Time: $(date)"
          if [[ "$OSTYPE" == "darwin"* ]]; then
            echo "OS: macOS"
            sw_vers
          else
            echo "OS: Linux"
            cat /etc/os-release
          fi
          echo "::endgroup::"

      - name: Update Casks
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: "AppleBlox/appleblox"
        run: |
          python3 scripts/update_casks.py

      - name: Commit and Push Changes
        run: |
          set -euo pipefail

          echo "[debug] Checking for changes..."
          git status

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            echo "[debug] Diff of changes to be committed:"
            git diff --cached

            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: update appleblox casks"
            git push
          fi
