name: Update AppleBlox Casks

on:
  schedule:
    - cron: "0 0 * * *" # Run daily
  workflow_dispatch: # Allow manual trigger
  workflow_call: # Allow triggering from other workflows

jobs:
  bump-casks:
    name: Update AppleBlox Casks
    runs-on: macos-26
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Debug Environment
        run: |
          echo "::group::System Information"
          echo "Time: $(date)"
          if [[ "$OSTYPE" == "darwin"* ]]; then
            echo "OS: macOS"
            sw_vers
          else
            echo "OS: Linux"
            cat /etc/os-release
          fi
          echo "::endgroup::"

      - name: Update Casks
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: "AppleBlox/appleblox"
        run: |
          python3 scripts/update_casks.py


